### ISSUE TITLE
Pass-through fileformats

### ISSUE THREAD

**Issue by rexxars** [rexxars/mead#16]
Since libvips doesn't currently support gif, it might be smart if we could still pass it through untouched from the source.  This should be configurable and allow multiple file formats, such as SVG, TIFF etc.

**Comment by rexxars** [comment]
A temporary solution for gifs and svgs have been implemented. Configuration is not available right now, so I'll leave this open.

**Comment by evenwestvang** [comment]
SVGs currently aren't completely pass-through and you can query for them in other formats. They appear to first be [rasterized and then scaled](https://cdn.sanity.io/images/723dcy9n/production/nKqMUw2eAXta_Tb91tPDiSMGxRwJG74JvO66P-222x344.svg?w=500&fm=png) instead of being rasterized in the exact width / height being queried for.
